#!/usr/bin/env bash
### Script that transfers a file to a server
### It accepts 4 parameters:
### * Path to the file
### * IP address of the server to transfer to
### * Username in server that scp connects with
### * The path to the SSH private key that scp uses

USAGE='Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'

if [ "$#" -ne 4 ]
then
	echo "$USAGE"
else
	FILE_PATH="$1"
	IP="$2"
	USERNAME="$3"
	IDENTITY_FILE="$4"  # SSH private key file
	scp -i "$IDENTITY_FILE" "$FILE_PATH" "$USERNAME"@"$IP":
fi
