#!/usr/bin/env bash
# A script that securely transport a file to a server

# Incomplete transport details
if [ $# -lt 3 ]
then
	echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	FILE=$1		# First argument passed
	IP=$2			# Second ...	
	USERNAME=$3		# Third ...
	SSH_KEY=$4	# Fourth ... Optional because it can be specified in config

	DESTINATION_DIR="/home/ubuntu"

	scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME"@"$IP":"$DESTINATION_DIR"
fi
