#!/usr/bin/env bash
# Redirects the url path: /redirect_me

sed -i -e '48 s/\//\/redirect_me/' /etc/nginx/sites-available/default
sed -i -e '51 s/try_files \(.*\)/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/' /etc/nginx/sites-available/default
