#!/usr/bin/env bash
# Sends 5 ICMP packets to the host at the provided IP address requesting responses

HOST="$1"

if [ $# -ne 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$HOST"
fi
