#!/usr/bin/env bash
# Prints the string "To infinity and beyond" indefinitely
# Prints "I am invincible!!!" when ever a SIGTERM signal is sent

trap "echo I am invincible!!!" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
